version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./pharmaco-frontend/Dockerfile
    ports:
      - "30444:30444"
  nginx:
    build:
      context: .
      dockerfile: "./nginx/Dockerfile"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/default.conf
    ports:
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge