# Generated by Django 3.1.4 on 2021-02-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precursors',
            fields=[
                ('UUID', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='UUID')),
                ('DrugID', models.CharField(max_length=100, verbose_name='DrugID')),
                ('DrugName', models.CharField(max_length=100, verbose_name='DrugName')),
                ('SmileCode', models.CharField(max_length=255, verbose_name='SmileCode')),
                ('InChiKey', models.CharField(max_length=100, verbose_name='InChiKey')),
                ('logp', models.DecimalField(decimal_places=20, max_digits=22, verbose_name='logp')),
                ('max_rmsd', models.DecimalField(decimal_places=20, max_digits=22, verbose_name='max_rmsd')),
            ],
            options={
                'db_table': 'precursors',
                'managed': True,
            },
        ),
    ]
