# Generated by Django 3.1.2 on 2020-12-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metabolite',
            fields=[
                ('UUID', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='UUID')),
                ('metabolite_InChi', models.CharField(max_length=4000, verbose_name='MetaboliteInchi')),
                ('metabolite_InChiKey', models.CharField(max_length=27, unique=True, verbose_name='MetaboliteInchiKey')),
                ('metabolite_smile_string', models.CharField(max_length=250, verbose_name='MetaboliteSmileString')),
                ('metab_ID', models.CharField(max_length=10, verbose_name='MetaboliteID')),
                ('reaction', models.CharField(max_length=45, verbose_name='Reaction')),
                ('reaction_ID', models.CharField(max_length=10, unique=True, verbose_name='ReactionID')),
                ('enzyme', models.CharField(max_length=45, verbose_name='Enzyme')),
                ('biosystem', models.CharField(max_length=45, verbose_name='Biosystem')),
                ('precursor_smiles', models.CharField(max_length=250, verbose_name='PrecursorSmiles')),
                ('precursor_InChi', models.CharField(max_length=400, unique=True, verbose_name='PrecursorInchi')),
                ('precursor_InChiKey', models.CharField(max_length=27, verbose_name='PrecursorInchiKey')),
            ],
            options={
                'db_table': 'metabolites',
                'managed': True,
            },
        ),
    ]
