# Generated by Django 3.1.4 on 2021-02-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecursorMetaboliteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precursor_UUID', models.CharField(max_length=36, verbose_name='precursor_UUID')),
                ('metabolite_UUID', models.CharField(max_length=36, verbose_name='metabolite_UUID')),
                ('origin', models.CharField(max_length=12, verbose_name='origin')),
            ],
            options={
                'db_table': 'precursor_metabolite_map',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Precursors',
            fields=[
                ('UUID', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='UUID')),
                ('DrugID', models.CharField(max_length=100, verbose_name='DrugID')),
                ('DrugName', models.CharField(max_length=100, verbose_name='DrugName')),
                ('SmileCode', models.CharField(max_length=255, verbose_name='SmileCode')),
                ('InChiKey', models.CharField(max_length=100, verbose_name='InChiKey')),
                ('logp', models.DecimalField(decimal_places=20, max_digits=22, verbose_name='logp')),
                ('max_rmsd', models.DecimalField(decimal_places=20, max_digits=22, verbose_name='max_rmsd')),
            ],
            options={
                'db_table': 'precursors',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='metabolite',
            name='biotrans_origin',
            field=models.CharField(default=None, max_length=20, verbose_name='biotrans_origin'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='logp',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=22, verbose_name='logp'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='max_rmsd',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=22, verbose_name='max_rmsd'),
        ),
    ]
