# Generated by Django 2.2.6 on 2020-03-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(max_length=100, verbose_name='Drug ID')),
                ('stereoisomer', models.CharField(max_length=100, verbose_name='Stereoisomer ID')),
                ('umls_concept_id', models.CharField(max_length=100, verbose_name='UMLS Concept ID')),
                ('frequency_percent', models.CharField(max_length=20, verbose_name='Frequency(%)')),
                ('frequency_lower', models.CharField(max_length=100, verbose_name='Frequency Lower')),
                ('frequency_upper', models.CharField(max_length=100, verbose_name='Frequency Upper')),
                ('concept_type', models.CharField(max_length=5, verbose_name='Concept Type')),
                ('side_effect', models.CharField(max_length=100, verbose_name='Side Effect')),
                ('drug_name', models.CharField(max_length=100, verbose_name='Drug Name')),
                ('atc_code', models.CharField(max_length=10, verbose_name='ATC Code')),
            ],
        ),
    ]
