# Generated by Django 2.2.6 on 2019-10-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=100)),
                ('gene_description', models.CharField(max_length=100)),
                ('tissue_type', models.CharField(max_length=100)),
                ('side_effect', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='GeTex',
        ),
    ]
