# Generated by Django 2.2.6 on 2019-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0002_auto_20191030_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sideeffect',
            old_name='gene_description',
            new_name='Drug ID',
        ),
        migrations.RenameField(
            model_name='sideeffect',
            old_name='gene_id',
            new_name='Drug Name',
        ),
        migrations.RenameField(
            model_name='sideeffect',
            old_name='side_effect',
            new_name='Placebo',
        ),
        migrations.RenameField(
            model_name='sideeffect',
            old_name='tissue_type',
            new_name='Side Effect',
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='Concept Type',
            field=models.CharField(default='PT', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='Frequency Lower',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='Frequency Upper',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='Frequency(%)',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='StereoIsomer',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='UMLS Concept ID',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='UMLS Concept ID2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
