# Generated by Django 2.2.6 on 2019-11-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0003_auto_20191106_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sideeffect',
            old_name='StereoIsomer',
            new_name='Stereoisomer',
        ),
    ]
