# Generated by Django 2.2.6 on 2019-11-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0004_auto_20191106_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sideeffect',
            old_name='Stereoisomer',
            new_name='Stereoisomer ID',
        ),
    ]
