# Generated by Django 2.2.6 on 2019-11-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0005_auto_20191107_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='ATC Code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
