# Generated by Django 2.2.6 on 2019-11-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0006_sideeffect_atc code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffect',
            name='ATC Code',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Concept Type',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Drug ID',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Drug Name',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Frequency Lower',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Frequency Upper',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Frequency(%)',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Placebo',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Side Effect',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='Stereoisomer ID',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='UMLS Concept ID',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='UMLS Concept ID2',
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='atc_code',
            field=models.CharField(default=None, max_length=10, verbose_name='ATC Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='concept_type',
            field=models.CharField(default=None, max_length=5, verbose_name='Concept Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='drug_id',
            field=models.CharField(default=None, max_length=100, verbose_name='Drug ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='drug_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Drug Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='frequency_lower',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5, verbose_name='Frequency Lower'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='frequency_percent',
            field=models.CharField(default=0.0, max_length=10, verbose_name='Frequency(%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='frequency_upper',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5, verbose_name='Frequency Upper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='placebo',
            field=models.CharField(default=None, max_length=100, verbose_name='Placebo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='side_effect',
            field=models.CharField(default=None, max_length=100, verbose_name='Side Effect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='stereoisomer',
            field=models.CharField(default=None, max_length=100, verbose_name='Stereoisomer ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='umls_concept_id',
            field=models.CharField(default=None, max_length=100, verbose_name='UMLS Concept ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='umls_concept_id2',
            field=models.CharField(default=None, max_length=100, verbose_name='UMLS Concept ID2'),
            preserve_default=False,
        ),
    ]
