# Generated by Django 2.2.6 on 2019-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0007_auto_20191107_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_lower',
            field=models.CharField(max_length=10, verbose_name='Frequency Lower'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_upper',
            field=models.CharField(max_length=10, verbose_name='Frequency Upper'),
        ),
    ]
