# Generated by Django 2.2.6 on 2019-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0008_auto_20191107_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffect',
            name='placebo',
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='umls_concept_id2',
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_lower',
            field=models.FloatField(max_length=10, verbose_name='Frequency Lower'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_percent',
            field=models.CharField(max_length=20, verbose_name='Frequency(%)'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_upper',
            field=models.FloatField(max_length=10, verbose_name='Frequency Upper'),
        ),
    ]
