# Generated by Django 2.2.6 on 2019-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacogenomics', '0009_auto_20191107_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_lower',
            field=models.FloatField(verbose_name='Frequency Lower'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='frequency_upper',
            field=models.FloatField(verbose_name='Frequency Upper'),
        ),
    ]
