version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: "./nginx/Dockerfile"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/default.conf
    ports:
      - "30441:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge