# Generated by Django 2.2.6 on 2020-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=20, verbose_name='Gene ID')),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
                ('adipose_subcutaneous', models.FloatField(max_length=10, verbose_name='Adipose-Subcutaneous')),
                ('adipose_visceral_omentum', models.FloatField(max_length=10, verbose_name='Adipose-Visceral(Omentum)')),
                ('adrenal_gland', models.FloatField(max_length=10, verbose_name='Adrenal-Gland')),
                ('artery_aorta', models.FloatField(max_length=10, verbose_name='Artery-Aorta')),
                ('artery_coronary', models.FloatField(max_length=10, verbose_name='Artery-Coronary')),
                ('artery_tibial', models.FloatField(max_length=10, verbose_name='Artery-Tibial')),
                ('bladder', models.FloatField(max_length=10, verbose_name='Bladder')),
                ('brain_amygdala', models.FloatField(max_length=10, verbose_name='Brain-Amygdala')),
                ('brain_anterior_cingulate_cortex_BA24', models.FloatField(max_length=10, verbose_name='Brain-Anterior-cingulate-cortex-(BA24)')),
                ('brain_caudate_basalganglia', models.FloatField(max_length=10, verbose_name='Brain-Caudate(basalganglia)')),
                ('brain_cerebral_hemisphere', models.FloatField(max_length=10, verbose_name='Brain-CerebellarHemisphere')),
                ('brain_cerebellum', models.FloatField(max_length=10, verbose_name='Brain-Cerebellum')),
                ('brain_cortex', models.FloatField(max_length=10, verbose_name='Brain-Cortex')),
                ('brain_frontal_cortex_BA9', models.FloatField(max_length=10, verbose_name='Brain-FrontalCortex(BA9)')),
                ('brain_hippocampus', models.FloatField(max_length=10, verbose_name='Brain-Hippocampus')),
                ('brain_hypothalamus', models.FloatField(max_length=10, verbose_name='Brain-Hypothalamus')),
                ('brain_nucleusaccumbens_basalganglia', models.FloatField(max_length=10, verbose_name='Brain-Nucleusaccumbens(basalganglia)')),
                ('brain_putamen_basalganglia', models.FloatField(max_length=10, verbose_name='Brain-Putamen(basalganglia)')),
                ('brain_spinalcord_cervicalc_1', models.FloatField(max_length=10, verbose_name='Brain-Spinalcord(cervicalc-1)')),
                ('brain_substantianigra', models.FloatField(max_length=10, verbose_name='Brain-Substantianigra')),
                ('breast_mammary_tissue', models.FloatField(max_length=10, verbose_name='Breast-MammaryTissue')),
                ('cells_cultured_fibroblasts', models.FloatField(max_length=10, verbose_name='Cells-Cultured-fibroblasts')),
                ('cells_ebv_transformed_lymphocytes', models.FloatField(max_length=10, verbose_name='Cells-EBV-transformedlymphocytes')),
                ('cervix_ectocervix', models.FloatField(max_length=10, verbose_name='Cervix-Ectocervix')),
                ('cervix_endocervix', models.FloatField(max_length=10, verbose_name='Cervix-Endocervix')),
                ('colon_sigmoid', models.FloatField(max_length=10, verbose_name='Colon-Sigmoid')),
                ('colon_transverse', models.FloatField(max_length=10, verbose_name='Colon-Transverse')),
                ('esophagus_gastroesophageal_junction', models.FloatField(max_length=10, verbose_name='Esophagus-GastroesophagealJunction')),
                ('esophagus_mucosa', models.FloatField(max_length=10, verbose_name='Esophagus-Mucosa')),
                ('esophagus_muscularis', models.FloatField(max_length=10, verbose_name='Esophagus-Muscularis')),
                ('fallopian_tube', models.FloatField(max_length=10, verbose_name='FallopianTube')),
                ('heart_atrial_appendage', models.FloatField(max_length=10, verbose_name='Heart-AtrialAppendage')),
                ('heart_left_ventricle', models.FloatField(max_length=10, verbose_name='Heart-LeftVentricle')),
                ('kidney_cortex', models.FloatField(max_length=10, verbose_name='Kidney-Cortex')),
                ('kidney_medulla', models.FloatField(max_length=10, verbose_name='Kidney-Medulla')),
                ('liver', models.FloatField(max_length=10, verbose_name='Liver')),
                ('lung', models.FloatField(max_length=10, verbose_name='Lung')),
                ('minor_salivary_gland', models.FloatField(max_length=10, verbose_name='MinorSalivaryGland')),
                ('muscle_skeletal', models.FloatField(max_length=10, verbose_name='Muscle-Skeletal')),
                ('nerve_tibial', models.FloatField(max_length=10, verbose_name='Nerve-Tibial')),
                ('ovary', models.FloatField(max_length=10, verbose_name='Ovary')),
                ('pancreas', models.FloatField(max_length=10, verbose_name='Pancreas')),
                ('pituitary', models.FloatField(max_length=10, verbose_name='Pituitary')),
                ('prostate', models.FloatField(max_length=10, verbose_name='Prostate')),
                ('skin_not_sun_exposed_suprapubic', models.FloatField(max_length=10, verbose_name='Skin-NotSunExposed(Suprapubic)')),
                ('skin_sun_exposed_lower_leg', models.FloatField(max_length=10, verbose_name='Skin-SunExposed(Lowerleg)')),
                ('small_intestine_terminal_ileum', models.FloatField(max_length=10, verbose_name='SmallIntestine-TerminalIleum')),
                ('spleen', models.FloatField(max_length=10, verbose_name='SmallIntestine-TerminalIleum')),
                ('stomach', models.FloatField(max_length=10, verbose_name='Stomach')),
                ('testis', models.FloatField(max_length=10, verbose_name='Testis')),
                ('thyroid', models.FloatField(max_length=10, verbose_name='Thyroid')),
                ('uterus', models.FloatField(max_length=10, verbose_name='Uterus')),
                ('vagina', models.FloatField(max_length=10, verbose_name='Vagina')),
                ('whole_blood', models.FloatField(max_length=10, verbose_name='WholeBlood')),
            ],
            options={
                'db_table': 'gtexome_gtex',
                'managed': True,
            },
        ),
    ]
