# Generated by Django 3.1.4 on 2022-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullMetaboliteMap',
            fields=[
                ('UUID', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='UUID')),
                ('precursor_UUID', models.CharField(max_length=36, verbose_name='UUID')),
                ('metabolite_UUID', models.CharField(max_length=36, verbose_name='UUID')),
                ('origin', models.CharField(max_length=12, verbose_name='origin')),
                ('level', models.IntegerField(verbose_name='level')),
            ],
            options={
                'db_table': 'full_metabolite_map',
                'managed': True,
            },
        ),
    ]
